version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: demo-shop

volumes:
  postgres-data: